version: '3'

volumes:
  postgres_volume_prod:

services:
  pg-chat:
    image: postgres:14-alpine3.17
    env_file:
      - prod.env
    ports:
      - "54324:5432"
    networks:
      - services-network
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  migrator-prod:
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-chat
    networks:
      - services-network

networks:
  services-network:
    name: service-net
    external: true
