version: '3'

volumes:
  postgres_volume_prod:

services:
  pg-prod:
    image: postgres:14-alpine3.17
    env_file:
      - prod.env
    ports:
      - "54324:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  migrator-prod-chat:
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-prod
